spring.application.name=WebAppVoli
spring.datasource.url=jdbc:postgresql://localhost:5432/webAppVoli
spring.datasource.username=postgres
spring.datasource.password=1999
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.hibernate.ddl-auto=update

token.expiration=900000
token.secret=chiavesegretachiavesegretachiavesegreta
